// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file common/v1/common.proto (package workforce.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export const file_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvY29tbW9uLnByb3RvEhN3b3JrZm9yY2UuY29tbW9uLnYxIjEKCURhdGVSYW5nZRISCgpzdGFydF9kYXRlGAEgASgJEhAKCGVuZF9kYXRlGAIgASgJImcKB0FkZHJlc3MSDQoFbGluZTEYASABKAkSDQoFbGluZTIYAiABKAkSDAoEY2l0eRgDIAEoCRINCgVzdGF0ZRgEIAEoCRIQCghwb3N0Y29kZRgFIAEoCRIPCgdjb3VudHJ5GAYgASgJIi4KBU1vbmV5Eg4KBmFtb3VudBgBIAEoAxIVCg1jdXJyZW5jeV9jb2RlGAIgASgJKksKCldvcmtlclR5cGUSGwoXV09SS0VSX1RZUEVfVU5TUEVDSUZJRUQQABIKCgZPRkZJQ0UQARIJCgVGSUVMRBACEgkKBU1JWEVEEAMqkAEKCUpvYlN0YXR1cxIaChZKT0JfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUSk9CX1NUQVRVU19TQ0hFRFVMRUQQARIaChZKT0JfU1RBVFVTX0lOX1BST0dSRVNTEAISFwoTSk9CX1NUQVRVU19DT01QTEVURRADEhgKFEpPQl9TVEFUVVNfQ0FOQ0VMTEVEEAQqmAEKC1NoaWZ0U3RhdHVzEhwKGFNISUZUX1NUQVRVU19VTlNQRUNJRklFRBAAEhoKFlNISUZUX1NUQVRVU19TQ0hFRFVMRUQQARIaChZTSElGVF9TVEFUVVNfQ09NUExFVEVEEAISFwoTU0hJRlRfU1RBVFVTX01JU1NFRBADEhoKFlNISUZUX1NUQVRVU19DQU5DRUxMRUQQBCp+CgxQYXlGcmVxdWVuY3kSHQoZUEFZX0ZSRVFVRU5DWV9VTlNQRUNJRklFRBAAEhgKFFBBWV9GUkVRVUVOQ1lfV0VFS0xZEAESGgoWUEFZX0ZSRVFVRU5DWV9CSVdFRUtMWRACEhkKFVBBWV9GUkVRVUVOQ1lfTU9OVEhMWRADQiZaJG90dG8vaW50ZXJuYWwvZ2VuL2NvbW1vbi92MTtjb21tb252MWIGcHJvdG8z");

/**
 * DateRange represents an inclusive calendar interval expressed as ISO 8601
 * date strings (YYYY-MM-DD).
 *
 * @generated from message workforce.common.v1.DateRange
 */
export type DateRange = Message<"workforce.common.v1.DateRange"> & {
  /**
   * First day of the range (inclusive), e.g. "2024-01-01".
   *
   * @generated from field: string start_date = 1;
   */
  startDate: string;

  /**
   * Last day of the range (inclusive), e.g. "2024-03-31".
   *
   * @generated from field: string end_date = 2;
   */
  endDate: string;
};

/**
 * Describes the message workforce.common.v1.DateRange.
 * Use `create(DateRangeSchema)` to create a new message.
 */
export const DateRangeSchema: GenMessage<DateRange> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 0);

/**
 * Address is a postal address suitable for both office and field locations.
 *
 * @generated from message workforce.common.v1.Address
 */
export type Address = Message<"workforce.common.v1.Address"> & {
  /**
   * Primary street line, e.g. "123 Main St".
   *
   * @generated from field: string line1 = 1;
   */
  line1: string;

  /**
   * Optional secondary line, e.g. "Suite 400".
   *
   * @generated from field: string line2 = 2;
   */
  line2: string;

  /**
   * @generated from field: string city = 3;
   */
  city: string;

  /**
   * State, province, or region code.
   *
   * @generated from field: string state = 4;
   */
  state: string;

  /**
   * Postal / ZIP code.
   *
   * @generated from field: string postcode = 5;
   */
  postcode: string;

  /**
   * ISO 3166-1 alpha-2 country code, e.g. "US".
   *
   * @generated from field: string country = 6;
   */
  country: string;
};

/**
 * Describes the message workforce.common.v1.Address.
 * Use `create(AddressSchema)` to create a new message.
 */
export const AddressSchema: GenMessage<Address> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 1);

/**
 * Money represents a monetary amount stored as integer cents to avoid
 * floating-point precision issues.
 *
 * @generated from message workforce.common.v1.Money
 */
export type Money = Message<"workforce.common.v1.Money"> & {
  /**
   * Amount in the smallest currency unit (cents for USD), e.g. 150000 = $1500.00.
   *
   * @generated from field: int64 amount = 1;
   */
  amount: bigint;

  /**
   * ISO 4217 currency code, e.g. "USD".
   *
   * @generated from field: string currency_code = 2;
   */
  currencyCode: string;
};

/**
 * Describes the message workforce.common.v1.Money.
 * Use `create(MoneySchema)` to create a new message.
 */
export const MoneySchema: GenMessage<Money> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 2);

/**
 * WorkerType classifies how an employee primarily performs their work.
 *
 * @generated from enum workforce.common.v1.WorkerType
 */
export enum WorkerType {
  /**
   * @generated from enum value: WORKER_TYPE_UNSPECIFIED = 0;
   */
  WORKER_TYPE_UNSPECIFIED = 0,

  /**
   * Primarily works from a fixed office location.
   *
   * @generated from enum value: OFFICE = 1;
   */
  OFFICE = 1,

  /**
   * Travels to external sites to perform work.
   *
   * @generated from enum value: FIELD = 2;
   */
  FIELD = 2,

  /**
   * Combination of office and field work.
   *
   * @generated from enum value: MIXED = 3;
   */
  MIXED = 3,
}

/**
 * Describes the enum workforce.common.v1.WorkerType.
 */
export const WorkerTypeSchema: GenEnum<WorkerType> = /*@__PURE__*/
  enumDesc(file_common_v1_common, 0);

/**
 * JobStatus tracks the lifecycle of a field job.
 *
 * @generated from enum workforce.common.v1.JobStatus
 */
export enum JobStatus {
  /**
   * @generated from enum value: JOB_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Job has been booked but work has not yet started.
   *
   * @generated from enum value: JOB_STATUS_SCHEDULED = 1;
   */
  SCHEDULED = 1,

  /**
   * Work is actively underway.
   *
   * @generated from enum value: JOB_STATUS_IN_PROGRESS = 2;
   */
  IN_PROGRESS = 2,

  /**
   * All work has been finished and the job is closed.
   *
   * @generated from enum value: JOB_STATUS_COMPLETE = 3;
   */
  COMPLETE = 3,

  /**
   * Job was called off before or during execution.
   *
   * @generated from enum value: JOB_STATUS_CANCELLED = 4;
   */
  CANCELLED = 4,
}

/**
 * Describes the enum workforce.common.v1.JobStatus.
 */
export const JobStatusSchema: GenEnum<JobStatus> = /*@__PURE__*/
  enumDesc(file_common_v1_common, 1);

/**
 * ShiftStatus tracks the state of an office / non-field shift.
 *
 * @generated from enum workforce.common.v1.ShiftStatus
 */
export enum ShiftStatus {
  /**
   * @generated from enum value: SHIFT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Shift is planned but has not yet occurred.
   *
   * @generated from enum value: SHIFT_STATUS_SCHEDULED = 1;
   */
  SCHEDULED = 1,

  /**
   * Employee worked the shift as planned.
   *
   * @generated from enum value: SHIFT_STATUS_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * Employee did not attend and gave no prior notice.
   *
   * @generated from enum value: SHIFT_STATUS_MISSED = 3;
   */
  MISSED = 3,

  /**
   * Shift was removed before it occurred.
   *
   * @generated from enum value: SHIFT_STATUS_CANCELLED = 4;
   */
  CANCELLED = 4,
}

/**
 * Describes the enum workforce.common.v1.ShiftStatus.
 */
export const ShiftStatusSchema: GenEnum<ShiftStatus> = /*@__PURE__*/
  enumDesc(file_common_v1_common, 2);

/**
 * PayFrequency describes how often an employee receives pay.
 *
 * @generated from enum workforce.common.v1.PayFrequency
 */
export enum PayFrequency {
  /**
   * @generated from enum value: PAY_FREQUENCY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Paid once every seven days.
   *
   * @generated from enum value: PAY_FREQUENCY_WEEKLY = 1;
   */
  WEEKLY = 1,

  /**
   * Paid once every two weeks.
   *
   * @generated from enum value: PAY_FREQUENCY_BIWEEKLY = 2;
   */
  BIWEEKLY = 2,

  /**
   * Paid once per calendar month.
   *
   * @generated from enum value: PAY_FREQUENCY_MONTHLY = 3;
   */
  MONTHLY = 3,
}

/**
 * Describes the enum workforce.common.v1.PayFrequency.
 */
export const PayFrequencySchema: GenEnum<PayFrequency> = /*@__PURE__*/
  enumDesc(file_common_v1_common, 3);

