// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file payroll/v1/payroll.proto (package workforce.payroll.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { DateRange, Money, PayFrequency } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file payroll/v1/payroll.proto.
 */
export const file_payroll_v1_payroll: GenFile = /*@__PURE__*/
  fileDesc("ChhwYXlyb2xsL3YxL3BheXJvbGwucHJvdG8SFHdvcmtmb3JjZS5wYXlyb2xsLnYxIsgBCgZQYXlSdW4SCgoCaWQYASABKAkSEwoLZW1wbG95ZWVfaWQYAiABKAkSFAoMcGVyaW9kX3N0YXJ0GAMgASgJEhIKCnBlcmlvZF9lbmQYBCABKAkSKQoFZ3Jvc3MYBSABKAsyGi53b3JrZm9yY2UuY29tbW9uLnYxLk1vbmV5EicKA25ldBgGIAEoCzIaLndvcmtmb3JjZS5jb21tb24udjEuTW9uZXkSDgoGc3RhdHVzGAcgASgJEg8KB3BhaWRfYXQYCCABKAkiUAoRR2V0UGF5cm9sbFJlcXVlc3QSEwoLZW1wbG95ZWVfaWQYASABKAkSFwoKcGF5X3BlcmlvZBgCIAEoCUgAiAEBQg0KC19wYXlfcGVyaW9kIlkKEkdldFBheXJvbGxSZXNwb25zZRITCgtlbXBsb3llZV9pZBgBIAEoCRIuCghwYXlfcnVucxgCIAMoCzIcLndvcmtmb3JjZS5wYXlyb2xsLnYxLlBheVJ1biKTAQoLUGF5U2NoZWR1bGUSCgoCaWQYASABKAkSEwoLZW1wbG95ZWVfaWQYAiABKAkSNAoJZnJlcXVlbmN5GAMgASgOMiEud29ya2ZvcmNlLmNvbW1vbi52MS5QYXlGcmVxdWVuY3kSFgoOZWZmZWN0aXZlX2RhdGUYBCABKAkSFQoNbmV4dF9wYXlfZGF0ZRgFIAEoCSIsChVHZXRQYXlTY2hlZHVsZVJlcXVlc3QSEwoLZW1wbG95ZWVfaWQYASABKAkikQEKEkxpc3RQYXlSdW5zUmVxdWVzdBITCgtlbXBsb3llZV9pZBgBIAEoCRI3CgpkYXRlX3JhbmdlGAIgASgLMh4ud29ya2ZvcmNlLmNvbW1vbi52MS5EYXRlUmFuZ2VIAIgBARITCgZzdGF0dXMYAyABKAlIAYgBAUINCgtfZGF0ZV9yYW5nZUIJCgdfc3RhdHVzIloKE0xpc3RQYXlSdW5zUmVzcG9uc2USLgoIcGF5X3J1bnMYASADKAsyHC53b3JrZm9yY2UucGF5cm9sbC52MS5QYXlSdW4SEwoLdG90YWxfY291bnQYAiABKAUytwIKDlBheXJvbGxTZXJ2aWNlEl8KCkdldFBheXJvbGwSJy53b3JrZm9yY2UucGF5cm9sbC52MS5HZXRQYXlyb2xsUmVxdWVzdBooLndvcmtmb3JjZS5wYXlyb2xsLnYxLkdldFBheXJvbGxSZXNwb25zZRJgCg5HZXRQYXlTY2hlZHVsZRIrLndvcmtmb3JjZS5wYXlyb2xsLnYxLkdldFBheVNjaGVkdWxlUmVxdWVzdBohLndvcmtmb3JjZS5wYXlyb2xsLnYxLlBheVNjaGVkdWxlEmIKC0xpc3RQYXlSdW5zEigud29ya2ZvcmNlLnBheXJvbGwudjEuTGlzdFBheVJ1bnNSZXF1ZXN0Gikud29ya2ZvcmNlLnBheXJvbGwudjEuTGlzdFBheVJ1bnNSZXNwb25zZUIoWiZvdHRvL2ludGVybmFsL2dlbi9wYXlyb2xsL3YxO3BheXJvbGx2MWIGcHJvdG8z", [file_common_v1_common]);

/**
 * PayRun represents a single pay disbursement for one employee.
 *
 * @generated from message workforce.payroll.v1.PayRun
 */
export type PayRun = Message<"workforce.payroll.v1.PayRun"> & {
  /**
   * Unique identifier for this pay run.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The employee this pay run belongs to.
   *
   * @generated from field: string employee_id = 2;
   */
  employeeId: string;

  /**
   * ISO 8601 date marking the start of the pay period.
   *
   * @generated from field: string period_start = 3;
   */
  periodStart: string;

  /**
   * ISO 8601 date marking the end of the pay period.
   *
   * @generated from field: string period_end = 4;
   */
  periodEnd: string;

  /**
   * Total earnings before deductions.
   *
   * @generated from field: workforce.common.v1.Money gross = 5;
   */
  gross?: Money | undefined;

  /**
   * Take-home amount after all deductions.
   *
   * @generated from field: workforce.common.v1.Money net = 6;
   */
  net?: Money | undefined;

  /**
   * Current processing state, e.g. "pending", "processed", "paid".
   *
   * @generated from field: string status = 7;
   */
  status: string;

  /**
   * ISO 8601 timestamp when the funds were disbursed; empty if not yet paid.
   *
   * @generated from field: string paid_at = 8;
   */
  paidAt: string;
};

/**
 * Describes the message workforce.payroll.v1.PayRun.
 * Use `create(PayRunSchema)` to create a new message.
 */
export const PayRunSchema: GenMessage<PayRun> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 0);

/**
 * GetPayrollRequest identifies an employee and an optional period qualifier.
 *
 * @generated from message workforce.payroll.v1.GetPayrollRequest
 */
export type GetPayrollRequest = Message<"workforce.payroll.v1.GetPayrollRequest"> & {
  /**
   * UUID of the employee whose payroll is being requested.
   *
   * @generated from field: string employee_id = 1;
   */
  employeeId: string;

  /**
   * Human-readable period selector such as "latest", "2024-Q1", or a
   * specific ISO 8601 date. Leave empty to return all runs.
   *
   * @generated from field: optional string pay_period = 2;
   */
  payPeriod?: string | undefined;
};

/**
 * Describes the message workforce.payroll.v1.GetPayrollRequest.
 * Use `create(GetPayrollRequestSchema)` to create a new message.
 */
export const GetPayrollRequestSchema: GenMessage<GetPayrollRequest> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 1);

/**
 * GetPayrollResponse returns all matching pay runs for the requested employee.
 *
 * @generated from message workforce.payroll.v1.GetPayrollResponse
 */
export type GetPayrollResponse = Message<"workforce.payroll.v1.GetPayrollResponse"> & {
  /**
   * The employee these pay runs belong to.
   *
   * @generated from field: string employee_id = 1;
   */
  employeeId: string;

  /**
   * @generated from field: repeated workforce.payroll.v1.PayRun pay_runs = 2;
   */
  payRuns: PayRun[];
};

/**
 * Describes the message workforce.payroll.v1.GetPayrollResponse.
 * Use `create(GetPayrollResponseSchema)` to create a new message.
 */
export const GetPayrollResponseSchema: GenMessage<GetPayrollResponse> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 2);

/**
 * PaySchedule describes when and how often an employee is paid.
 *
 * @generated from message workforce.payroll.v1.PaySchedule
 */
export type PaySchedule = Message<"workforce.payroll.v1.PaySchedule"> & {
  /**
   * Unique identifier for this schedule record.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The employee this schedule applies to.
   *
   * @generated from field: string employee_id = 2;
   */
  employeeId: string;

  /**
   * How often the employee is paid.
   *
   * @generated from field: workforce.common.v1.PayFrequency frequency = 3;
   */
  frequency: PayFrequency;

  /**
   * ISO 8601 date from which this schedule takes effect.
   *
   * @generated from field: string effective_date = 4;
   */
  effectiveDate: string;

  /**
   * ISO 8601 date of the next upcoming pay disbursement.
   *
   * @generated from field: string next_pay_date = 5;
   */
  nextPayDate: string;
};

/**
 * Describes the message workforce.payroll.v1.PaySchedule.
 * Use `create(PayScheduleSchema)` to create a new message.
 */
export const PayScheduleSchema: GenMessage<PaySchedule> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 3);

/**
 * GetPayScheduleRequest identifies the employee whose schedule is needed.
 *
 * @generated from message workforce.payroll.v1.GetPayScheduleRequest
 */
export type GetPayScheduleRequest = Message<"workforce.payroll.v1.GetPayScheduleRequest"> & {
  /**
   * @generated from field: string employee_id = 1;
   */
  employeeId: string;
};

/**
 * Describes the message workforce.payroll.v1.GetPayScheduleRequest.
 * Use `create(GetPayScheduleRequestSchema)` to create a new message.
 */
export const GetPayScheduleRequestSchema: GenMessage<GetPayScheduleRequest> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 4);

/**
 * ListPayRunsRequest supports rich filtering of pay-run history.
 *
 * @generated from message workforce.payroll.v1.ListPayRunsRequest
 */
export type ListPayRunsRequest = Message<"workforce.payroll.v1.ListPayRunsRequest"> & {
  /**
   * UUID of the employee whose pay runs are being listed.
   *
   * @generated from field: string employee_id = 1;
   */
  employeeId: string;

  /**
   * When set, restricts results to pay runs whose period overlaps this range.
   *
   * @generated from field: optional workforce.common.v1.DateRange date_range = 2;
   */
  dateRange?: DateRange | undefined;

  /**
   * When set, restricts results to pay runs with this status string.
   *
   * @generated from field: optional string status = 3;
   */
  status?: string | undefined;
};

/**
 * Describes the message workforce.payroll.v1.ListPayRunsRequest.
 * Use `create(ListPayRunsRequestSchema)` to create a new message.
 */
export const ListPayRunsRequestSchema: GenMessage<ListPayRunsRequest> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 5);

/**
 * ListPayRunsResponse carries the filtered pay-run list with a total count.
 *
 * @generated from message workforce.payroll.v1.ListPayRunsResponse
 */
export type ListPayRunsResponse = Message<"workforce.payroll.v1.ListPayRunsResponse"> & {
  /**
   * @generated from field: repeated workforce.payroll.v1.PayRun pay_runs = 1;
   */
  payRuns: PayRun[];

  /**
   * Total number of pay runs matching the filter (before any pagination).
   *
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;
};

/**
 * Describes the message workforce.payroll.v1.ListPayRunsResponse.
 * Use `create(ListPayRunsResponseSchema)` to create a new message.
 */
export const ListPayRunsResponseSchema: GenMessage<ListPayRunsResponse> = /*@__PURE__*/
  messageDesc(file_payroll_v1_payroll, 6);

/**
 * @generated from service workforce.payroll.v1.PayrollService
 */
export const PayrollService: GenService<{
  /**
   * GetPayroll retrieves one or more pay-run records for an employee,
   * optionally scoped to a named period such as "latest" or "2024-Q1".
   *
   * @generated from rpc workforce.payroll.v1.PayrollService.GetPayroll
   */
  getPayroll: {
    methodKind: "unary";
    input: typeof GetPayrollRequestSchema;
    output: typeof GetPayrollResponseSchema;
  },
  /**
   * GetPaySchedule returns the active pay schedule for an employee,
   * including pay frequency and the next anticipated pay date.
   *
   * @generated from rpc workforce.payroll.v1.PayrollService.GetPaySchedule
   */
  getPaySchedule: {
    methodKind: "unary";
    input: typeof GetPayScheduleRequestSchema;
    output: typeof PayScheduleSchema;
  },
  /**
   * ListPayRuns returns a filterable, paginated list of pay-run records
   * for an employee, optionally scoped by date range and/or status.
   *
   * @generated from rpc workforce.payroll.v1.PayrollService.ListPayRuns
   */
  listPayRuns: {
    methodKind: "unary";
    input: typeof ListPayRunsRequestSchema;
    output: typeof ListPayRunsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_payroll_v1_payroll, 0);

