// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file payroll/v1/payroll.proto (package workforce.payroll.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CalculatePayPreviewRequest, GetPayRatesRequest, GetPayrollRequest, GetPayrollResponse, GetPayScheduleRequest, ListPayRunsRequest, ListPayRunsResponse, PayPreview, PayRates, PaySchedule, SetPayRatesRequest } from "./payroll_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service workforce.payroll.v1.PayrollService
 */
export const PayrollService = {
  typeName: "workforce.payroll.v1.PayrollService",
  methods: {
    /**
     * GetPayroll retrieves one or more pay-run records for an employee,
     * optionally scoped to a named period such as "latest" or "2024-Q1".
     *
     * @generated from rpc workforce.payroll.v1.PayrollService.GetPayroll
     */
    getPayroll: {
      name: "GetPayroll",
      I: GetPayrollRequest,
      O: GetPayrollResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetPaySchedule returns the active pay schedule for an employee,
     * including pay frequency and the next anticipated pay date.
     *
     * @generated from rpc workforce.payroll.v1.PayrollService.GetPaySchedule
     */
    getPaySchedule: {
      name: "GetPaySchedule",
      I: GetPayScheduleRequest,
      O: PaySchedule,
      kind: MethodKind.Unary,
    },
    /**
     * ListPayRuns returns a filterable, paginated list of pay-run records
     * for an employee, optionally scoped by date range and/or status.
     *
     * @generated from rpc workforce.payroll.v1.PayrollService.ListPayRuns
     */
    listPayRuns: {
      name: "ListPayRuns",
      I: ListPayRunsRequest,
      O: ListPayRunsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetPayRates returns the configured hourly rate card for an employee
     * (day, night, weekend, and overtime rates).
     *
     * @generated from rpc workforce.payroll.v1.PayrollService.GetPayRates
     */
    getPayRates: {
      name: "GetPayRates",
      I: GetPayRatesRequest,
      O: PayRates,
      kind: MethodKind.Unary,
    },
    /**
     * SetPayRates creates or replaces the hourly rate card for an employee.
     *
     * @generated from rpc workforce.payroll.v1.PayrollService.SetPayRates
     */
    setPayRates: {
      name: "SetPayRates",
      I: SetPayRatesRequest,
      O: PayRates,
      kind: MethodKind.Unary,
    },
    /**
     * CalculatePayPreview computes a real-time pay breakdown for an employee
     * across a date range, applying day/night/weekend/overtime rates to each
     * logged shift, and projects an end-of-period total from scheduled shifts.
     *
     * @generated from rpc workforce.payroll.v1.PayrollService.CalculatePayPreview
     */
    calculatePayPreview: {
      name: "CalculatePayPreview",
      I: CalculatePayPreviewRequest,
      O: PayPreview,
      kind: MethodKind.Unary,
    },
  }
} as const;

