// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file employee/v1/employee.proto (package workforce.employee.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { WorkerType } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file employee/v1/employee.proto.
 */
export const file_employee_v1_employee: GenFile = /*@__PURE__*/
  fileDesc("ChplbXBsb3llZS92MS9lbXBsb3llZS5wcm90bxIVd29ya2ZvcmNlLmVtcGxveWVlLnYxIpEBCghFbXBsb3llZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEhIKCmRlcGFydG1lbnQYBCABKAkSNAoLd29ya2VyX3R5cGUYBSABKA4yHy53b3JrZm9yY2UuY29tbW9uLnYxLldvcmtlclR5cGUSEgoKY3JlYXRlZF9hdBgGIAEoCSI8ChJHZXRFbXBsb3llZVJlcXVlc3QSDAoCaWQYASABKAlIABIOCgRuYW1lGAIgASgJSABCCAoGbG9va3VwIokBChRMaXN0RW1wbG95ZWVzUmVxdWVzdBIXCgpkZXBhcnRtZW50GAEgASgJSACIAQESOQoLd29ya2VyX3R5cGUYAiABKA4yHy53b3JrZm9yY2UuY29tbW9uLnYxLldvcmtlclR5cGVIAYgBAUINCgtfZGVwYXJ0bWVudEIOCgxfd29ya2VyX3R5cGUiYAoVTGlzdEVtcGxveWVlc1Jlc3BvbnNlEjIKCWVtcGxveWVlcxgBIAMoCzIfLndvcmtmb3JjZS5lbXBsb3llZS52MS5FbXBsb3llZRITCgt0b3RhbF9jb3VudBgCIAEoBTLYAQoPRW1wbG95ZWVTZXJ2aWNlElkKC0dldEVtcGxveWVlEikud29ya2ZvcmNlLmVtcGxveWVlLnYxLkdldEVtcGxveWVlUmVxdWVzdBofLndvcmtmb3JjZS5lbXBsb3llZS52MS5FbXBsb3llZRJqCg1MaXN0RW1wbG95ZWVzEisud29ya2ZvcmNlLmVtcGxveWVlLnYxLkxpc3RFbXBsb3llZXNSZXF1ZXN0Giwud29ya2ZvcmNlLmVtcGxveWVlLnYxLkxpc3RFbXBsb3llZXNSZXNwb25zZUIqWihvdHRvL2ludGVybmFsL2dlbi9lbXBsb3llZS92MTtlbXBsb3llZXYxYgZwcm90bzM", [file_common_v1_common]);

/**
 * Employee is the canonical identity record for a member of the workforce.
 * It is the source of truth for employee_id referenced by other services.
 *
 * @generated from message workforce.employee.v1.Employee
 */
export type Employee = Message<"workforce.employee.v1.Employee"> & {
  /**
   * Globally unique identifier (UUID v4).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Full display name of the employee.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Work email address.
   *
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * Organisational department, e.g. "Engineering".
   *
   * @generated from field: string department = 4;
   */
  department: string;

  /**
   * Classifies how the employee primarily performs their work.
   *
   * @generated from field: workforce.common.v1.WorkerType worker_type = 5;
   */
  workerType: WorkerType;

  /**
   * ISO 8601 timestamp when the employee record was created.
   *
   * @generated from field: string created_at = 6;
   */
  createdAt: string;
};

/**
 * Describes the message workforce.employee.v1.Employee.
 * Use `create(EmployeeSchema)` to create a new message.
 */
export const EmployeeSchema: GenMessage<Employee> = /*@__PURE__*/
  messageDesc(file_employee_v1_employee, 0);

/**
 * GetEmployeeRequest looks up a single employee.
 * Exactly one of id or name must be supplied.
 *
 * @generated from message workforce.employee.v1.GetEmployeeRequest
 */
export type GetEmployeeRequest = Message<"workforce.employee.v1.GetEmployeeRequest"> & {
  /**
   * @generated from oneof workforce.employee.v1.GetEmployeeRequest.lookup
   */
  lookup: {
    /**
     * Exact match on the employee UUID.
     *
     * @generated from field: string id = 1;
     */
    value: string;
    case: "id";
  } | {
    /**
     * Case-insensitive partial match on the employee's name (ILIKE "%name%").
     *
     * @generated from field: string name = 2;
     */
    value: string;
    case: "name";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message workforce.employee.v1.GetEmployeeRequest.
 * Use `create(GetEmployeeRequestSchema)` to create a new message.
 */
export const GetEmployeeRequestSchema: GenMessage<GetEmployeeRequest> = /*@__PURE__*/
  messageDesc(file_employee_v1_employee, 1);

/**
 * ListEmployeesRequest supports optional server-side filtering.
 *
 * @generated from message workforce.employee.v1.ListEmployeesRequest
 */
export type ListEmployeesRequest = Message<"workforce.employee.v1.ListEmployeesRequest"> & {
  /**
   * When set, restrict results to employees in this department.
   *
   * @generated from field: optional string department = 1;
   */
  department?: string | undefined;

  /**
   * When set, restrict results to employees of this worker type.
   *
   * @generated from field: optional workforce.common.v1.WorkerType worker_type = 2;
   */
  workerType?: WorkerType | undefined;
};

/**
 * Describes the message workforce.employee.v1.ListEmployeesRequest.
 * Use `create(ListEmployeesRequestSchema)` to create a new message.
 */
export const ListEmployeesRequestSchema: GenMessage<ListEmployeesRequest> = /*@__PURE__*/
  messageDesc(file_employee_v1_employee, 2);

/**
 * ListEmployeesResponse carries the filtered result set.
 *
 * @generated from message workforce.employee.v1.ListEmployeesResponse
 */
export type ListEmployeesResponse = Message<"workforce.employee.v1.ListEmployeesResponse"> & {
  /**
   * @generated from field: repeated workforce.employee.v1.Employee employees = 1;
   */
  employees: Employee[];

  /**
   * Total number of employees matching the filter (before any pagination).
   *
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;
};

/**
 * Describes the message workforce.employee.v1.ListEmployeesResponse.
 * Use `create(ListEmployeesResponseSchema)` to create a new message.
 */
export const ListEmployeesResponseSchema: GenMessage<ListEmployeesResponse> = /*@__PURE__*/
  messageDesc(file_employee_v1_employee, 3);

/**
 * @generated from service workforce.employee.v1.EmployeeService
 */
export const EmployeeService: GenService<{
  /**
   * GetEmployee fetches a single employee by UUID or by name (fuzzy ILIKE
   * match). Returns NOT_FOUND if no matching record exists.
   *
   * @generated from rpc workforce.employee.v1.EmployeeService.GetEmployee
   */
  getEmployee: {
    methodKind: "unary";
    input: typeof GetEmployeeRequestSchema;
    output: typeof EmployeeSchema;
  },
  /**
   * ListEmployees returns a paginated list of employees with optional
   * filtering by department and/or worker type.
   *
   * @generated from rpc workforce.employee.v1.EmployeeService.ListEmployees
   */
  listEmployees: {
    methodKind: "unary";
    input: typeof ListEmployeesRequestSchema;
    output: typeof ListEmployeesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_employee_v1_employee, 0);

