// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file employee/v1/employee.proto (package workforce.employee.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Employee, GetEmployeeRequest, ListEmployeesRequest, ListEmployeesResponse } from "./employee_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service workforce.employee.v1.EmployeeService
 */
export const EmployeeService = {
  typeName: "workforce.employee.v1.EmployeeService",
  methods: {
    /**
     * GetEmployee fetches a single employee by UUID or by name (fuzzy ILIKE
     * match). Returns NOT_FOUND if no matching record exists.
     *
     * @generated from rpc workforce.employee.v1.EmployeeService.GetEmployee
     */
    getEmployee: {
      name: "GetEmployee",
      I: GetEmployeeRequest,
      O: Employee,
      kind: MethodKind.Unary,
    },
    /**
     * ListEmployees returns a paginated list of employees with optional
     * filtering by department and/or worker type.
     *
     * @generated from rpc workforce.employee.v1.EmployeeService.ListEmployees
     */
    listEmployees: {
      name: "ListEmployees",
      I: ListEmployeesRequest,
      O: ListEmployeesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

