// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file scheduling/v1/scheduling.proto (package workforce.scheduling.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateShiftRequest, GetAvailabilityRequest, GetAvailabilityResponse, GetShiftRequest, ListShiftsRequest, ListShiftsResponse, Shift, TimeOffRequest, TimeOffResponse, UpdateShiftRequest } from "./scheduling_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service workforce.scheduling.v1.SchedulingService
 */
export const SchedulingService = {
  typeName: "workforce.scheduling.v1.SchedulingService",
  methods: {
    /**
     * CreateShift books a new office or non-field shift for an employee.
     *
     * @generated from rpc workforce.scheduling.v1.SchedulingService.CreateShift
     */
    createShift: {
      name: "CreateShift",
      I: CreateShiftRequest,
      O: Shift,
      kind: MethodKind.Unary,
    },
    /**
     * GetShift retrieves a single shift record by its UUID.
     *
     * @generated from rpc workforce.scheduling.v1.SchedulingService.GetShift
     */
    getShift: {
      name: "GetShift",
      I: GetShiftRequest,
      O: Shift,
      kind: MethodKind.Unary,
    },
    /**
     * ListShifts returns all shifts for an employee, with optional filtering
     * by date range and/or shift status.
     *
     * @generated from rpc workforce.scheduling.v1.SchedulingService.ListShifts
     */
    listShifts: {
      name: "ListShifts",
      I: ListShiftsRequest,
      O: ListShiftsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateShift performs a partial update on a shift; only fields present
     * in the request are modified, all others are left unchanged.
     *
     * @generated from rpc workforce.scheduling.v1.SchedulingService.UpdateShift
     */
    updateShift: {
      name: "UpdateShift",
      I: UpdateShiftRequest,
      O: Shift,
      kind: MethodKind.Unary,
    },
    /**
     * RequestTimeOff submits a leave request on behalf of an employee and
     * returns an approval decision with an explanatory message.
     *
     * @generated from rpc workforce.scheduling.v1.SchedulingService.RequestTimeOff
     */
    requestTimeOff: {
      name: "RequestTimeOff",
      I: TimeOffRequest,
      O: TimeOffResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAvailability returns all scheduled shifts and recorded days off for
     * an employee within the requested date range.
     *
     * @generated from rpc workforce.scheduling.v1.SchedulingService.GetAvailability
     */
    getAvailability: {
      name: "GetAvailability",
      I: GetAvailabilityRequest,
      O: GetAvailabilityResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

