// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file job/v1/job.proto (package workforce.job.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AssignEmployeesRequest, CreateJobRequest, GetJobLocationRequest, GetJobRequest, Job, JobLocation, ListJobsRequest, ListJobsResponse, UpdateJobStatusRequest } from "./job_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service workforce.job.v1.JobService
 */
export const JobService = {
  typeName: "workforce.job.v1.JobService",
  methods: {
    /**
     * CreateJob registers a new field job with location, description, and
     * the planned schedule window; employees are assigned separately.
     *
     * @generated from rpc workforce.job.v1.JobService.CreateJob
     */
    createJob: {
      name: "CreateJob",
      I: CreateJobRequest,
      O: Job,
      kind: MethodKind.Unary,
    },
    /**
     * GetJob retrieves a single job record by its UUID.
     *
     * @generated from rpc workforce.job.v1.JobService.GetJob
     */
    getJob: {
      name: "GetJob",
      I: GetJobRequest,
      O: Job,
      kind: MethodKind.Unary,
    },
    /**
     * ListJobs returns a filterable list of jobs, supporting filters by
     * assigned employee, date range, status, and city.
     *
     * @generated from rpc workforce.job.v1.JobService.ListJobs
     */
    listJobs: {
      name: "ListJobs",
      I: ListJobsRequest,
      O: ListJobsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AssignEmployees appends one or more employees to a job's assignment list
     * without replacing any existing assignments.
     *
     * @generated from rpc workforce.job.v1.JobService.AssignEmployees
     */
    assignEmployees: {
      name: "AssignEmployees",
      I: AssignEmployeesRequest,
      O: Job,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateJobStatus transitions a job to a new lifecycle state and
     * optionally records the actual start and/or end timestamps.
     *
     * @generated from rpc workforce.job.v1.JobService.UpdateJobStatus
     */
    updateJobStatus: {
      name: "UpdateJobStatus",
      I: UpdateJobStatusRequest,
      O: Job,
      kind: MethodKind.Unary,
    },
    /**
     * GetJobLocation returns the address and GPS coordinates for a job,
     * useful for routing and map display in field applications.
     *
     * @generated from rpc workforce.job.v1.JobService.GetJobLocation
     */
    getJobLocation: {
      name: "GetJobLocation",
      I: GetJobLocationRequest,
      O: JobLocation,
      kind: MethodKind.Unary,
    },
  }
} as const;

